#!/bin/bash
sxhkd &
picom --config ~/.config/picom/picom.conf &
~/.config/polybar/launch.sh &
feh --bg-scale ~/Pictures/wallpapers/wall-01.webp

bspc monitor -d I II III IV V VI
bspc config focus_follows_pointer     true
bspc config border_width 0

pgrep -x dunst > /dev/null || dunst &