#!/bin/bash

# Фикс курсора
xsetroot -cursor_name left_ptr

# Запуск xsettingsd (GTK тема и иконки)
pgrep -x xsettingsd > /dev/null || xsettingsd &

# Запуск необходимых программ
pgrep -x sxhkd > /dev/null || sxhkd &
picom --config ~/.config/picom/picom.conf &
~/.config/polybar/launch.sh &
feh --bg-scale ~/Pictures/Wallpapers/wall-03.jpg

# Настройка рабочих столов
bspc monitor -d      
bspc config focus_follows_pointer true

# Window borders
bspc config focused_border_color "#7899FA"
bspc config normal_border_color "#1f222b"
bspc config border_width 1
bspc config borderless_monocle true
bspc config active_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

# Gaps
bspc config gapless_monocle false
bspc config window_gap 17

# Pointer actions
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# Xresources
xrdb merge ~/.Xresources

# Window rules
bspc rule -a librewolf desktop = '^1' follow=on state=tiled
bspc rule -a kitty desktop = '^2' follow=on state=tiled
bspc rule -a code desktop = '^2' follow=on state=tiled
bspc rule -a Telegram desktop='^4' follow=on state=tiled
bspc rule -a discord desktop='^4' follow=on state=tiled
bspc rule -a Spotify desktop='^5' follow=on state=tiled
bspc rule -a steam desktop = '^6' follow=on state=tiled

# Яркость и автозапуск
brightnessctl set 100%
pgrep -x dunst > /dev/null || dunst &
pgrep -x spotify || spotify &
pgrep -x Telegram || Telegram &
